global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ec2'
    ec2_sd_configs:
      - region: 'us-west-2'
        access_key: 'AWS_ACCESS_KEY'
        secret_key: 'AWS_SECRET_KEY'
        port: 9100
    relabel_configs:
      - source_labels: [__meta_ec2_private_dns_name]
        target_label: instance

rule_files:
  - alerts.rules

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']